# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  locationsearchweb:
    image: locationsearchweb
    build:
      context: .
      dockerfile: location.search.web/Dockerfile
    ports:
      - 9001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9001
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
